//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_programmering_RGB.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colors
    {
        public int Id { get; set; }
        public string ColorCode { get; set; }
    }
}
